# some scripting inspiration from: https://github.com/winterfest-2020/unwrap-parcel/blob/master/.github/workflows/issue-ops-encrypt-content.yaml
name: IssueOps - Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Extract project labels
      id: extract
      uses: actions/github-script@v4
      # env:
      #     labels: ${{ toJSON(github.event.issue.labels) }}
      with:
          # github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            //const { local_labels } = process.env.labels;
            // Are we really supposed to access the payload? context.issue does
            // not contain the labels for some reason.
            const local_labels = context.payload.issue.labels;
            let project_number = -1

            //const { data: local_labels } = await github.issues.listLabelsOnIssue({
            //  owner: context.repo.owner,
            //  repo: context.repo.repo,
            //  issue_number: context.issue.number,
            //});
            //console.log(local_labels)

            for (const label of local_labels) {
              if (label.name.match(/^project_(.*)/)) {
                let project_number = label.name.match(/^project_(.*)/)[1]
                console.log("Project Number extracted from label: " + project_number)
              }
            }

            const { data: projects } = await github.projects.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            let local_project
            for (const project of projects) {
              console.log(project)
              if (project.number == project_number) {
                local_project = project
              }
            }
            console.log(local_project)

            //const project = await github.projects.get({
            //  project_number,
            //});
            //console.log(project)




    # - name: Assign issues and pull requests to project 1 ("Website Building")
    #   uses: srggrs/assign-one-project-github-action@1.2.1
    #   if: |
    #     (contains(github.event.issue.labels.*.name, 'website') ||
    #     contains(github.event.pull_request.labels.*.name, 'website'))
    #   with:
    #     project: 'https://github.com/spier/gha-auto-project-assignment/projects/1'
    # - name: Assign issues and pull requests to project 2 ("Other Things")
    #   uses: srggrs/assign-one-project-github-action@1.2.1
    #   if: |
    #     (contains(github.event.issue.labels.*.name, 'other') ||
    #     contains(github.event.pull_request.labels.*.name, 'other'))
    #   with:
    #     project: 'https://github.com/spier/gha-auto-project-assignment/projects/2'
